{% set name = "python-can" %}
{% set version = "4.0.0" %}
{% set sha256 = "59d92846ffb981e634e9e0f2d14a6b4967a875e3869bd2ba168c92c4db6b8b5d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - msgpack
    - packaging
    - python
    - pyserial
    - pywin32
    - setuptools
    - typing
    - typing_extensions >=3.10.0.0
    - windows-curses
    - wrapt

test:
  imports:
    - can
    - can.interfaces
    - can.interfaces.etas
    - can.interfaces.ics_neovi
    - can.interfaces.ixxat
    - can.interfaces.kvaser
    - can.interfaces.neousys
    - can.interfaces.pcan
    - can.interfaces.seeedstudio
    - can.interfaces.serial
    - can.interfaces.socketcan
    - can.interfaces.socketcand
    - can.interfaces.systec
    - can.interfaces.udp_multicast
    - can.interfaces.usb2can
    - can.interfaces.vector
    - can.io

about:
  home: https://github.com/hardbyte/python-can
  license: LGPLv3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'The can package provides controller area network support for Python developers '
  description: |
    The **C**\ ontroller **A**\ rea **N**\ etwork is a bus standard designed
    to allow microcontrollers and devices to communicate with each other. It
    has priority based bus arbitration, reliable deterministic
    communication. It is used in cars, trucks, boats, wheelchairs and more.
    The ``can`` package provides controller area network support for
    Python developers; providing `common abstractions to
    different hardware devices`, and a suite of utilities for sending and receiving
    messages on a can bus.
    The library supports Python 2.7, Python 3.4+ as well as PyPy 2 & 3 and runs on Mac, Linux and Windows.

  doc_url: https://python-can.readthedocs.org/en/stable/
  dev_url: https://github.com/hardbyte/python-can

extra:
  recipe-maintainers:
    - hardbyte
    - danielhrisca
