{% set version = "4.5.0" %}

package:
  name: python-can
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python_can/python_can-{{ version }}.tar.gz
  sha256: d3684cebe5b028a148c1742b3a45cec4fcaf83a7f7c52d0680b2eaeaf52f8eb7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - msgpack-python
    - packaging
    - python >={{ python_min }}
    - pyserial
    - typing
    - typing_extensions >=3.10.0.0
    - wrapt >=1.10.0
    # - pywin32         # [win]
    # - windows-curses  # [win]

test:
  requires:
    - python {{ python_min }}
  imports:
    - can
    - can.interfaces
#    - can.interfaces.etas
#    - can.interfaces.ics_neovi
#    - can.interfaces.ixxat
#    - can.interfaces.kvaser
#    - can.interfaces.neousys
#    - can.interfaces.pcan
#    - can.interfaces.seeedstudio
    - can.interfaces.serial
    - can.interfaces.socketcan
    - can.interfaces.socketcand
#    - can.interfaces.systec
    - can.interfaces.udp_multicast
#    - can.interfaces.usb2can
#    - can.interfaces.vector
    - can.io

about:
  home: https://github.com/hardbyte/python-can
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'The can package provides controller area network support for Python developers '
  description: |
    The **C**\ ontroller **A**\ rea **N**\ etwork is a bus standard designed
    to allow microcontrollers and devices to communicate with each other. It
    has priority based bus arbitration and reliable deterministic
    communication. It is used in cars, trucks, boats, wheelchairs and more.

    The ``can`` package provides controller area network support for
    Python developers; providing common abstractions to
    different hardware devices, and a suite of utilities for sending and receiving
    messages on a can bus.

    The library currently supports CPython as well as PyPy and runs on Mac, Linux and Windows.

    ==============================  ===========
    Library Version                 Python
    ------------------------------  -----------
      2.x                           2.6+, 3.4+
      3.x                           2.7+, 3.5+
      4.x *(currently on develop)*  3.7+
    ==============================  ===========


    Features
    --------

    - common abstractions for CAN communication
    - support for many different backends (see the `docs <https://python-can.readthedocs.io/en/stable/interfaces.html>`__)
    - receiving, sending, and periodically sending messages
    - normal and extended arbitration IDs
    - `CAN FD <https://en.wikipedia.org/wiki/CAN_FD>`__ support
    - many different loggers and readers supporting playback: ASC (CANalyzer format), BLF (Binary Logging Format by Vector), CSV, SQLite and Canutils log
    - efficient in-kernel or in-hardware filtering of messages on supported interfaces
    - bus configuration reading from a file or from environment variables
    - command line tools for working with CAN buses (see the `docs <https://python-can.readthedocs.io/en/stable/scripts.html>`__)
    - more

  doc_url: https://python-can.readthedocs.org/en/stable/
  dev_url: https://github.com/hardbyte/python-can

extra:
  recipe-maintainers:
    - hardbyte
    - danielhrisca
    - hmaarrfk
